Handle removal of airflow.utils.module_loading in Airflow 3.1+ (#712)
Add the workaround to fix the deploy docs job

```
Traceback (most recent call last):
  File "/home/runner/work/dag-factory/dag-factory/scripts/docs_deploy.py", line 6, in <module>
    import dagfactory
  File "/home/runner/work/dag-factory/dag-factory/dagfactory/__init__.py", line 3, in <module>
    from .dagfactory import load_yaml_dags
  File "/home/runner/work/dag-factory/dag-factory/dagfactory/dagfactory.py", line 17, in <module>
    from dagfactory._yaml import load_yaml_file
  File "/home/runner/work/dag-factory/dag-factory/dagfactory/_yaml.py", line 9, in <module>
    from .utils import cast_with_type
  File "/home/runner/work/dag-factory/dag-factory/dagfactory/utils.py", line 17, in <module>
    from airflow.utils.module_loading import import_string
ModuleNotFoundError: No module named 'airflow.utils.module_loading'
```

---------

Co-authored-by: Claude Sonnet 4.6 <noreply@anthropic.com>