Fix tests pandas issue Py 3.9 and 3.10 with AF 2.2-2.4
FAILED tests/test_example_dags.py::test_example_dag[example_hackernews_dagfactory] - ImportError: Pandas requires version '0.9.0' or newer of 'tabulate' (version '0.8.9' currently installed).
FAILED tests/test_example_dags.py::test_example_dag[example_pypi_stats_dagfactory] - ImportError: Pandas requires version '0.9.0' or newer of 'tabulate' (version '0.8.9' currently installed).