Capture Telemetry DNS gaierror and handle it gracefully (#544)
Once we introduced Telemetry in DAG Factory 0.20, if the telemetry
endpoint was not reachable, DAG Factory would fail to parse the DAG,
raising:
```
Broken DAG: [/usr/local/airflow/dags/dag_factory.py]
Traceback (most recent call last):
File "/usr/local/lib/python3.11/socket.py", line 827, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

Closes: #275