Bump versions of docs examples
Skipping 2.4 because:
FAILED tests/test_example_dags.py::test_example_dag[example_hackernews_dagfactory] - ImportError: Pandas requires version '0.9.0' or newer of 'tabulate' (version '0.8.10' currently installed).
FAILED tests/test_example_dags.py::test_example_dag[example_pypi_stats_dagfactory] - ImportError: Pandas requires version '0.9.0' or newer of 'tabulate' (version '0.8.10' currently installed).

Skipping 2.3 because:
ERROR tests/test_example_dags.py - AssertionError: assert not {'/home/runner/work/dag-factory/dag-factory/dev/dags/comparison/example_hackernews_plain_airflow.py': 'Traceback (most...ne, start_date=datetime(2022, 3, 4)) as dag:\nTypeError: __init__() got an unexpected keyword argument \'schedule\'\n'}
 +  where {'/home/runner/work/dag-factory/dag-factory/dev/dags/comparison/example_hackernews_plain_airflow.py': 'Traceback (most...ne, start_date=datetime(2022, 3, 4)) as dag:\nTypeError: __init__() got an unexpected keyword argument \'schedule\'\n'} =

Skipping 2.2 due to:
same issue as 2.3